### ISSUE TITLE
Example of usage with grunt-postcss

### ISSUE THREAD

**Issue by neilhem** [2createStudio/postcss-sprites#18]
Does somebody add how-to configure example of this plugin with grunt-postcss?

**Comment by vvasilev-** [comment]
The configuration of the plugin for grunt-postcss should be fairly simple. You can check the docs https://github.com/nDmitry/grunt-postcss#usage.

```js
grunt.initConfig({
  postcss: {
    options: {
      processors: [
        require('postcss-sprites')({
          // your config here
        })
      ]
    },
    dist: {
      src: 'css/*.css'
    }
  }
});
```

**Comment by neilhem** [comment]
Hi, thanks for a help. I have the same config as shown in above example. Is there way create sprite image right after postcss task has been executed? Seems like it happens later, in my case after some tasks which run after postcss.

**Comment by vvasilev-** [comment]
Can you give me an example of your config for grunt to make some tests?
