### ISSUE TITLE
PostCSS Plugins Guidelines

### ISSUE THREAD

**Issue by ai** [2createStudio/postcss-sprites#2]
[PostCSS Plugins Guidelines](https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md) are ondatory for all PostCSS plugins. You need quickly fix:

* [x] 1.4 Create plugin by `postcss.plugin`
* [x] 2.1. Plugin must be tested
* [x] 4.2. Put input and output examples
* [x] 4.4. `postcss-plugin` keyword in `package.json`

I suggested a 2 steps plan. We need to fix 1.4, 4.2 and 4.4 today and test can be written on this week.

/cc @vvasilev-

**Comment by vvasilev-** [comment]
Thanks for the feedback.

Point 1.4 is already done, so can you see it [here](https://github.com/2createStudio/postcss-sprites/blob/master/index.js#L58) and the tests will be added as soon as possible.
