### ISSUE TITLE
Support PostCSS 5.x

### ISSUE THREAD

**Issue by jedmao** [2createStudio/postcss-sprites#20]
https://github.com/postcss/postcss/releases/tag/5.0.0

**Comment by jedmao** [comment]
I think this should be a major version bump, because if I'm using PostCSS 4.x and this plugin updates automatically to PostCSS 5.x then it breaks all my other plugins on the PostCSS 4.x path.

**Comment by vvasilev-** [comment]
Thanks for the feedback :). A new major version was bumped.
