### ISSUE TITLE
SpritePath with variable.

### ISSUE THREAD

**Issue by fenvenfen** [2createStudio/postcss-sprites#21]
Hi, i  have problem with spritePath.
This is me postcss-sprite

 var opts = {
      stylesheetPath: 'wwwroot/css/main.css',
      spritePath: 'wwwroot/i/sprite.png',
      retina: true
  }

  require('postcss-sprites')({
                  stylesheetPath: '<%= opts.stylesheetPath %>',
                  spritePath: '<%= opts.spritePath %>',
              }),

And when i run  this task 
[postcss-sprites] => Error: Error: EEXIST, file already exists

**Comment by vvasilev-** [comment]
Hi.

I think that your configuration should be something like this:

````javascript
var opts = {
	styleSheetPath: 'wwwroot/css',
	spritePath    : 'wwwroot/i/sprite.png',
	retina        : true
}
````

Your ``styleSheetPath`` should point to a folder not to a file.
