### ISSUE TITLE
Add imagePath option

### ISSUE THREAD

**Issue by silvenon** [2createStudio/postcss-sprites#23]
This would enable postcss-sprite to resolve `url('/images/...')` paths. If you like the idea, I could submit a PR.

**Comment by vvasilev-** [comment]
Hello, I will be happy if you can submit a PR because I don't have time to implement this feature at the moment. :)

**Comment by silvenon** [comment]
Sure. I can implement it as an array which defines the order where to look for images.

**Awesome** plugin, by the way. It solves many issues I've been having, especially having to hardcode image dimensions in HTML/CSS.

**Comment by jackyjieliu** [comment]
Hi, I am wondering why this issue was closed. I would like this feature for my project because I have css and images in different directories. I can try to submit a pr if you guys are busy.

**Comment by silvenon** [comment]
@jackyjieliu I think it was closed due to my lack of response (sorry). I moved away from image sprites, so my motivation is not that strong anymore. Feel free to submit a PR :+1:

**Comment by jackyjieliu** [comment]
I was able to do what I was looking for after upgrading to the latest version. Thanks
