### ISSUE TITLE
why the output.css didn't solve the prop of 'background-repeat'

### ISSUE THREAD

**Issue by cnt1992** [2createStudio/postcss-sprites#30]
hi,I'm use this 'postcss-sprites' plugin,but I found that you didn't solve the prop of 'background-repeat',why?

**Comment by vvasilev-** [comment]
The plugin doesn't handle the `background-repeat` because most of sprites doesn't need it.
Can you explain your use case?

**Comment by cnt1992** [comment]
yeah,you are right,most of sprites doesn't use `background-repeat`,thank you very much~
