### ISSUE TITLE
why the “background-repeat” is missing？ 

### ISSUE THREAD

**Issue by ideayuye** [2createStudio/postcss-sprites#32]
I have a question.
my css like this：

    background: url('images/iconfont-wuliuguanli.png') no-repeat;

postcss-sprites process result like this:

    background-image: url(images/sprite.png);
    background-position: 0 0;

Why the "no-repeat" is missing?Thanks in advance!

**Comment by vvasilev-** [comment]
The plugin doesn't handle the`` background-repeat`` property because most of sprites doesn't need it.
Can you explain your use case?

**Comment by ideayuye** [comment]
@vvasilev-  thank you for your anwser! I waw wrong .Sprites really doesn't need it . I was really embarrassed for asked the question.
