### ISSUE TITLE
How to use in gulp?

### ISSUE THREAD

**Issue by shawx** [2createStudio/postcss-sprites#37]
This my configuration files,but it doesn't work...
How to configure the file properly？
<pre>
<code>
gulp.task('css', function () {
	var opts = {
		stylesheetPath: './dest',
		spritePath: './dest/images/'
	};
	var processors = [
		autoprefixer,
		cssnext,
		precss,
		sprites(opts)
	];
	return gulp.src('./src/*.css')
	.pipe(sourcemaps.init())
	.pipe(postcss(processors))
	.pipe(sourcemaps.write('.'))
	.pipe(gulp.dest('./dest'));
});
</code>
</pre>

thanks.

**Comment by cnt1992** [comment]
HI,when I use catch an error:
```
TypeError: sprites is not a function
```
How to fixed it?

**Comment by tanc** [comment]
I'm also seeing a similar error when trying to use this with gulp and postcss: TypeError: object is not a function

**Comment by tanc** [comment]
@shawx can you re-open this ticket? Unless you have a solution in which case can you post the solution?

**Comment by vvasilev-** [comment]
The problem was in dropped support for ``module.exports`` in ``babel-plugin-transform-es2015-modules-commonjs``. Now everything should work as expected.

/cc @shawx @tanc @cnt1992

**Comment by vvasilev-** [comment]
Use a slightly different require.

```
var sprites = require('postcss-sprites').default;
```

See [Kill CommonJS default export behaviour - babel/babel#2212](https://phabricator.babeljs.io/T2212)

**Comment by shawx** [comment]
@vvasilev- thx,It's helpful,My friend also found the problem.

**Comment by wklc2014** [comment]
@shawx Your gulp task is working or not? I use this plugin with gulp like you and it was not work, Do you resove it?

**Comment by shawx** [comment]
@wklc2014 `var sprites = require('postcss-sprites').default;`
vvasilev given the answer.
