### ISSUE TITLE
Question. How to avoid sprites overwriting

### ISSUE THREAD

**Issue by NXTaar** [2createStudio/postcss-sprites#43]
Here is my file structure
![structure](https://cloud.githubusercontent.com/assets/8634095/13744498/1e816008-e9f9-11e5-9900-48762e18bd7b.JPG)

I'm using webpack

sidebar/icons.scss
```
.actionExit {
    background: url("images/exit.png");
    size: 26px 20px;
}

.actionMenu {
    background: url("images/menu.png");
    size: 19px 13px;
}

.actionStat {
    background: url("images/graph.png");
    size: 24px 20px;
}

//and so on
```

dashboard-notifications-area/styles.scss

```
.bubble {
    position: relative;
    top: 20px;
    left: 20px;
    size: 108px;
    background: url("bubble.png");
    color: white;
    text-align: center;
}
```

plugin configuration
```
sprites( {
            spritesmith: { padding: 10 },
            spritePath: './dist/assets'
        })
```
When it compiles the output is like
```
postcss-sprites: 0 spritesheet generated.
postcss-sprites: 0 spritesheet generated.
postcss-sprites: 0 spritesheet generated.
postcss-sprites: 1 spritesheet generated.
postcss-sprites: 1 spritesheet generated.
```
It generates two different spritesheets for each `.scss` file, and obviously the second, overrides the first one, and i get in the sprite.png only the sprite for ```bubble.png```

How to tell the plugin to merge all of it to one file, and don't create a new `sprite.png` per each `.scss` file

**Comment by vvasilev-** [comment]
You need a single entry point so just combine your CSS files and pass them to the plugin.

**Comment by NXTaar** [comment]
Unfortunately i can't do that, because my components are independent, and they don't have a single entry point

**Comment by vvasilev-** [comment]
I think that there is no way to get working this, because webpack will process your files independently.

**Comment by NXTaar** [comment]
Ok, thanks for help. Will try something other way

**Comment by YingshanDeng** [comment]
@NXTaar  I have the same problem like you.  https://github.com/YingshanDeng/polymer-generate-spritesheet And now do you have a solution ?

**Comment by vvasilev-** [comment]
@YingshanDeng, You can use [groupBy](https://github.com/2createStudio/postcss-sprites/blob/master/examples/group-by.md) option to create a separate spritesheet per component.

**Comment by YingshanDeng** [comment]
Hello @vvasilev-  what i need is generate all the component into one spritesheet. and it is my demo: https://github.com/YingshanDeng/polymer-generate-spritesheet  but has some problem.

**Comment by Martin-Mo** [comment]
To combine all images into one sprite.png, you could try the following way:

1.Creating a mixin named "_sprites.scss" and writing all sprite related classes here

2.Extending the css classes mentioned above in your component's style file.
