### ISSUE TITLE
How to change the name of spritesheet

### ISSUE THREAD

**Issue by lolenko** [2createStudio/postcss-sprites#47]

**Comment by lolenko** [comment]
As i see there is hardcoded "sprite" name. But i realy need to build different bundles for every site page. And i don't want to create special folders for that. It'll be cool if you add this param. Thanks

**Comment by vvasilev-** [comment]
You can use the [Skip Prefix](https://github.com/2createStudio/postcss-sprites/blob/master/examples/skip-prefix.md) example. Also you see [here](https://github.com/2createStudio/postcss-sprites/blob/master/src/index.js#L572) what is the default behavior of the plugin
