### ISSUE TITLE
config sprite filename

### ISSUE THREAD

**Issue by Tommassissimo** [2createStudio/postcss-sprites#48]
I want to split css file for each html page and I use gulp with less and postcss, so I have multi less entries. And the result generating sprite for each less entry which is correct, but the filename for the sprite is no readable, as shown below, there is anywhere to config it?
![image](https://cloud.githubusercontent.com/assets/1832223/14549936/f8288c9e-02f6-11e6-9a46-030393d75e34.png)

**Comment by vvasilev-** [comment]
You can use Skip Prefix example to change the name of sprite. Also see
issue #47.

**Comment by Tommassissimo** [comment]
thanks, it solved my problem
