### ISSUE TITLE
[Question] Prevent re-declare background-image

### ISSUE THREAD

**Issue by arianraptor** [2createStudio/postcss-sprites#49]
Hello, is there any way to prevent declaring `background-image` again and again?
```
.comment { background-image: url(images/sprite.png); background-position: 0 0; }
.bubble { background-image: url(images/sprite.png); background-position: 0 -50px; }
```
i expect just like these following lines.
```
.icon { background-image: url(images/sprite.png); }
.comment { background-position: 0 0; }
.bubble { background-position: 0 -50px; }
```
Thanks for built an amazing plugins :smile:

**Comment by vvasilev-** [comment]
Hi,

You can use something like [Data Packer](https://github.com/Ser-Gen/postcss-data-packer) or [Merge Rules](https://github.com/ben-eb/postcss-merge-rules) to achieve this. :smile:

**Comment by arianraptor** [comment]
Thanks @vvasilev- for those solutions although i'm not satisfied yet :cry:, because i think defining like these following html syntax would be better.
```
<i class="icon comment">
```
Can u convince me that repeating background-image a lot considered good practices?

**Comment by vvasilev-** [comment]
Repeating of `background-image` is not a good practice but is necessary to use this plugin. The behavior that you want isn't in scope of this project so you can try to find an existing solution or create your own. :smile:

**Comment by arianraptor** [comment]
Again thanks @vvasilev- i'm satisfied now haha, really i'm not saying that this plugin is not good, i just need a reason to convince my team to use this plugin (for the sake of maintainability).
