### ISSUE TITLE
Promise rejections throw warning

### ISSUE THREAD

**Issue by niksy** [2createStudio/postcss-sprites#56]
As of v3.2.1, I get the following error in CLI output:

```sh
Warning: a promise was rejected with a non-error: [object Undefined]
```

I suppose it’s related to https://github.com/2createStudio/postcss-sprites/commit/4b897c0e2bf12d40a5905eca73d96d1f5841faec and Bluebird promises handling: http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-rejected-with-a-non-error

**Comment by kyohei8** [comment]
I got same warning.
```
Warning: a promise was rejected with a non-error: [object Undefined]
    at /Users/username/work/dev/node_modules/postcss-sprites/lib/index.js:176:30
    at /Users/username/work/dev/node_modules/postcss-sprites/lib/index.js:268:11
...
```
`prepareGroupBy` is it the same problem?

**Comment by jedmao** [comment]
I'm getting the same issue on version 4.1.1.

**Comment by jedmao** [comment]
It's [this line](https://github.com/2createStudio/postcss-sprites/blob/9ae47c94989e27a3bfdbb42076e70d601e135211/src/core.js#L113) for sure.
