### ISSUE TITLE
Avoiding flicker on hover (Chrome)

### ISSUE THREAD

**Issue by arianraptor** [2createStudio/postcss-sprites#60]
Hello, how you guys avoid flickering for non visible element at first loading using this plugin?
http://programming.mvergel.com/2012/11/chrome-reloads-sprite-image-on-css.html

Thank you

**Comment by vvasilev-** [comment]
Hello @arianraptor, we don't do anything about this but you can use [postcss-merge-rules](https://github.com/ben-eb/postcss-merge-rules) to merge the `background-image` declarations.
