### ISSUE TITLE
Spritesheet image buffer as argument to onSaveSpritesheet

### ISSUE THREAD

**Issue by niksy** [2createStudio/postcss-sprites#62]
Would it be possible (and make sense) to add final spritesheet buffer image as argument to `onSaveSpritesheet` hook?

Use case: you want to name your final files based on exact content inside those images, and you would hash final filename with module like [hasha](https://github.com/sindresorhus/hasha). This way you always get final filename inside your styles based on exact content. Currently the only way I can see that you can get different filename is with some external argument, but you loose caching of large images even if they didn’t change. With hashing final buffer this is avoided.

**Comment by niksy** [comment]
@vvasilev- have you had any chance to look at this?

**Comment by vvasilev-** [comment]
I'll look at this on Friday.
