### ISSUE TITLE
Use babel-plugin-add-module-exports

### ISSUE THREAD

**Issue by ai** [2createStudio/postcss-sprites#64]
Babel@6 drops support for CommonJS interop, but there is special plugin [babel-plugin-add-module-exports](https://github.com/59naga/babel-plugin-add-module-exports) to fix it.

Right now, you must do `require('postcss-sprites').default`, but it is hard in postcss-cli.

@vasilev- also PostCSS core uses babel-plugin-add-module-exports too.

**Comment by ai** [comment]
@vvasilev- any updates?

**Comment by vvasilev-** [comment]
Sorry for late response but I have few days off. I'll fix the issue at
Friday. 😀

**Comment by ai** [comment]
👍
