### ISSUE TITLE
Hook on spritesheet creation

### ISSUE THREAD

**Issue by niksy** [2createStudio/postcss-sprites#66]
Would it make sense to have hook when spritesheet is created?

One use case for this is image optimization with tool like [imagemin](https://github.com/imagemin/imagemin) where you could [act on spritesheet image buffer and optimize it](https://github.com/imagemin/imagemin#imageminbufferbuffer-options) before it is saved (similar to [`transform` for postcss-copy](https://github.com/geut/postcss-copy#-transform)). This could be done in separate process like Gulp plugin or plugin like [postcss-copy](https://github.com/geut/postcss-copy), but it seems like this could be nice addition to whole sprite generate process.
- One possible way for this hook: hook will expect promise resolve or reject like `filterBy` and `groupBy` where you would resolve with new spritesheet object.
- Or, maybe more in way of current implementation: adjust `onSaveSpritesheet` hook to have possibility of returning spritesheet object:
  - keep current implementation where if you return string it is final path for spritesheet
  - if you return promise with spritesheet object, use that as new spritesheet value
  - if you return promise with spritesheet path string, use that as new spritesheet final path (using promises is also keeping it within current async implementation)
- Maybe have option for optimization, where you would say you want to optimize your final image, and provide options to imagemin plugins.
  - Pros: simple and using known solution
  - Cons: not decoupled enough, not flexible enough if you want to have custom implementation for optimization algorithm

I’m leaning to solution number 2; open to modification and left to developers and how they want to handle final output.

---

Example:

``` js
sprites({
    // ...
    hooks: {
        onSaveSpritesheet: ( opts, spritesheet ) => {
            return imagemin.buffer(spritesheet.image, {
                plugins: [
                    imageminPngquant()
                ]
            }).then(( buff ) => {
                return Object.assign({}, spritesheet, {
                    image: buff
                });
            });
        }
    }
})
```

---

What do you think? Is this too much?

**Comment by vvasilev-** [comment]
I think that will be a nice addition to the plugin. Can you make a PR for this one?

**Comment by niksy** [comment]
Sure, will get on it as soon I make time!

**Comment by niksy** [comment]
@vvasilev- I’ve made the PR https://github.com/2createStudio/postcss-sprites/pull/70

Sorry this took so long :/
