### ISSUE TITLE
Usе with webpack and svg?

### ISSUE THREAD

**Issue by maximusnikulin** [2createStudio/postcss-sprites#67]
Can I use it with webpack and svg? I tried to make it work but I didn't do it. I began with using with png and generally it worked, but when I used svg instead png  format, I had an issue about unknown format. Besides, there is some problem with relevant paths. 
So can you write me some config to see how it can be implemented, if it can at all.
Thanks.

**Comment by vvasilev-** [comment]
Can you give more information about your setup and which version of the plugin you use?
