### ISSUE TITLE
Skipped images do not appear

### ISSUE THREAD

**Issue by callumacrae** [2createStudio/postcss-sprites#8]
If I skip an image, this happens:

```css
#home-buttons a.what-is			{ /*@replace|../images/images/hb-what-is-phpbb.png*/ }
#home-buttons a.get-started		{ /*@replace|../images/images/hb-get-started.png*/ }
#home-buttons a.enhance			{ /*@replace|../images/images/hb-enhance-phpbb.png*/ }
#home-buttons a.contribute		{ /*@replace|../images/images/hb-contribute.png*/ }
```

Why? Wouldn't it be better to leave it as is and let the browser handle the error, instead of dying silently?

Thanks for this plugin, by the way! looks like it is going to be super useful

**Comment by vvasilev-** [comment]
Sorry for late response, but I was off these days. 
The bug is fixed in [this commit](https://github.com/2createStudio/postcss-sprites/commit/2945541529c2716c2fe477f3cff8c9367bdbd35c) and I will update the package in npm today.

**Comment by vvasilev-** [comment]
npm version updated.
