### ISSUE TITLE
how to use in Webpack 3

### ISSUE THREAD

**Issue by rustam87** [2createStudio/postcss-sprites#97]
How to use  in Webpack 3? Is it  possible?
And how to use with spritesmith options in Webpack(for generate sprite png and scss files)

**Comment by vvasilev-** [comment]
@rustam87 

Yes, the plugin can be used with any version of webpack. You can see [here](https://github.com/postcss/postcss-loader) how to configure any PostCSS plugin that will be used by webpack.
